service: pseek-api

provider:
  name: aws
  runtime: nodejs10.x
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
      
functions:
  test:
    role: arn:aws:iam::606218893881:role/TeamRole
    handler: handlers/index.handler
    events: 
        - http:
            path: /hello-world
            method: post
            cors: true

plugins:
  - serverless-offline
