service: pSeek-api

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
      
functions:
  test:
    handler: handlers/index.handler
    events: 
        - http:
            path: /hello-world
            method: post
            cors: true

plugins:
  - serverless-offline
